---
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    build:
      context: ./requirements/mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    environment:
      WP_TITLE: "My WordPress Site"
      WP_ADMIN_USER: "admin"
      WP_ADMIN_PASSWORD: "admin_password"   # Corrected password to match your environment variables
      WP_ADMIN_EMAIL: "admin@example.com"
      WP_USER: "editor"
      WP_EMAIL: "editor@example.com"
      WP_PASSWORD: "editor_password"   # Corrected password to match your environment variables
      WP_DATABASE: "wordpress_db"   # Corrected database name
      WP_URL: "https://ctommasi.42.fr"
    volumes:
      - wp-files:/var/www/wordpress
    networks:
      - inception

  nginx:
    image: nginx
    container_name: nginx 
    restart: always
    build:
      context: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wp-files:/var/www/wordpress
    networks:
      - inception
      

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  db:
    name: "db"
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /home/ctommasi/data/db
  wp-files:
    name: "wp-files"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ctommasi/data/wp-files