services:
  nginx:
    image: nginx
    container_name: nginx 
    restart: always
    build:
      context: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wp-files:/var/www/wordpress
    networks:
      - inception

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    build:
      context: ./requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wp-files:/var/www/wordpress
    networks:
      - inception
    environment:
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_EMAIL: ${WP_EMAIL}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_DATABASE: ${WP_DATABASE}
      WP_URL: ${WP_URL}

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  db:
    name: "db"
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /home/ctommasi/data/db
  wp-files:
    name: "wp-files"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ctommasi/data/wp-files
