services:

  nginx:
    image: nginx
    container_name: nginx 
    build:
      context: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wp-files:/var/www/wordpress
      - certs:/etc/nginx/certs
      - html-files:/var/www/static_website
    networks:
      - inception
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wp-files:/var/www/wordpress
    networks:
      - inception
    environment:
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_EMAIL: ${WP_EMAIL}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_DATABASE: ${WP_DATABASE}
      WP_URL: ${WP_URL}
      WP_REDIS_HOST: ${WP_REDIS_HOST}
      WP_REDIS_PORT: ${WP_REDIS_PORT}
      WP_REDIS_SCHEME: ${WP_REDIS_SCHEME}
    restart: always
  
  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
    ports:
      - 6379:6379
    networks:
      - inception
    restart: always
  
  ftp:
    container_name: ftp
    build:
      context: ./requirements/bonus/FTP
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASSWORD: ${FTP_PASSWORD} 
    depends_on:
      - wordpress
    ports:
      - "21:21"
    volumes:
      - wp-files:/var/www/wordpress
    networks:
      - inception
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASSWORD: ${FTP_PASSWORD}
    restart: always

  static_website:
    container_name: static_website
    build:
      context: ./requirements/bonus/static_website
    volumes:
      - certs:/etc/nginx/certs
      - html-files:/var/www/static_website
    networks:
      - inception
    restart: always

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  db:
    name: "db"
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /home/ctommasi/data/db
  wp-files:
    name: "wp-files"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ctommasi/data/wp-files
  html-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ctommasi/data/html-files
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ctommasi/data/certs